Small Update to "Writing a Kubernetes Operator"
metalbear-co/metalbear.co pull request #104
Opened 2024-10-22 16:51 UTC by DmitryDodzin

Change article a bit to clarify the difference between api-service and controller

2024-10-31 13:33 UTC, eyalb181 requested changes

2024-10-31 13:33 UTC, eyalb181 commented on content/en/blog/kubernetes-operator/index.md
> +The operator pattern can be quite ambiguous, and we found the guides that currently exist for it to be quite dense and technical. In this post, I want to instead take a step-by-step approach and prov
```suggestion
The operator pattern can be quite ambiguous, and we found the guides that currently exist for it to be quite dense and technical. In this post, I want to instead take a step-by-step approach and provide a quick start for newcomers looking to explore the APIService flavor of the operator pattern.
```

2024-10-31 13:33 UTC, eyalb181 commented on content/en/blog/kubernetes-operator/index.md
> +Using a Kubernetes operators and CRD's can make it easier for your users to setup and configure your product on their cluster. Let’s illustrate this with an example: [CockroachDB](https://www.cockroa
```suggestion
Using  Kubernetes operators and CRDs can make it easier for your users to setup and configure your product on their cluster. Let’s illustrate this with an example: [CockroachDB](https://www.cockroachlabs.com/) is a sharded database with a Postgres-compatible API. Unlike PostgreSQL, it has some safety features enabled by default like requiring SSL encrypted connections for writes, so to deploy CockroachDB you would theoretically need to create and maintain a certificate for each of its Deployments on your Kubernetes cluster. For this reason, they created cockroach-operator. Once installed, a new resource named CrdbCluster becomes available. Whenever the user wants to create a new CockroachDB cluster, they now only have to create a new CrdbCluster object, and the [cockroach-operator](https://github.com/cockroachdb/cockroach-operator) takes care of the rest. 
```

2024-10-31 13:33 UTC, eyalb181 commented on content/en/blog/kubernetes-operator/index.md
> +An **APIService** is an extension to actual kubelet-api that allows you to create virtual CustomResourceDefinitions that don't exist in etcd and allows you to implement more advanced verbs manualy or
```suggestion
An **APIService** is an extension to actual Kubelet API that allows you to:
- Create virtual CustomResourceDefinitions that don't exist in etcd 
- Implement more advanced verbs manually 
- Use the Kubernetes API to expose more APIs like `kubectl auth can-i` api that uses `SelfSubjectAccessReview` (a `create` only api that expects no or an empty `metadata` field).
```

2024-10-31 13:33 UTC, eyalb181 commented on content/en/blog/kubernetes-operator/index.md
> +An **APIService** is an extension to actual kubelet-api that allows you to create virtual CustomResourceDefinitions that don't exist in etcd and allows you to implement more advanced verbs manualy or
@DmitryDodzin wdym by "expects no"?

2024-10-31 13:33 UTC, eyalb181 commented on content/en/blog/kubernetes-operator/index.md
> +For "mirrord for Teams" we use a mixture of APIService and Controller patterns where some of our CustomResourceDefinitions are managed by Controllers and some are exposed via an APIService.
```suggestion
For "mirrord for Teams" we use a mixture of the APIService and Controller patterns where some of our CustomResourceDefinitions are managed by Controllers and some are exposed via an APIService.
```

2024-10-31 13:33 UTC, eyalb181 commented on content/en/blog/kubernetes-operator/index.md
> +In the sections that follow, we’ll be creating an operator with an APIService since Controller pattern is pretty well documented and is the more popular approach of writing operators. But if you do n
```suggestion
In the sections that follow, we’ll be creating an operator with an APIService. The Controller pattern is pretty well documented and is the more popular approach for writing operator, but if you do need the extra flexibility or unique features that APIService provides, this tutorial will explain what Kubernetes expects of your operator to be a valid APIService. We’ll use Rust, but implementations in other languages can be extrapolated from it fairly easily, as it's mainly an HTTPS server that is very similar to the actual Kubernetes API. First, clone our [example repository](https://github.com/metalbear-co/farm-operator):
```

2025-03-23 08:10 UTC, aviramha commented
should we close this?

2025-04-24 21:58 UTC, aviramha commented
@DmitryDodzin @eyalb181 ?

2025-04-26 18:51 UTC, eyalb181 commented
@aviramha No, we'll wrap it up

2025-04-27 09:32 UTC, eyalb181 approved these changes

2025-04-27 09:43 UTC, merged