Kubecon blog
metalbear-co/metalbear.co pull request #106
Opened 2024-10-31 10:27 UTC by Anita-ihuman

Uploading Lorena's article for KubeCon

2024-11-03 17:43 UTC, eyalb181 requested changes

2024-11-04 12:13 UTC, lorena-mtz commented on content/en/blog/why-should-you-prioritize-the-mirrord-booth-at-kubecon?/index.md
> +title: "Why should you prioritize the mirrord booth at KubeCon?"
New title: Discover mirrord’s approach to fast, cloud-connected local dev at KubeCon

2024-11-04 14:00 UTC, eyalb181 approved these changes

2024-11-04 14:00 UTC, eyalb181 approved these changes

2024-11-04 14:00 UTC, eyalb181 commented on content/en/blog/discover-mirrord’s-approach-to-fast-cloud-connected-local-dev-at-kubecon/index.md
> +date: 2024-10-31T00:00:00+00:00
@Anita-ihuman Lets just changes this to today's date

2024-11-04 19:06 UTC, eyalb181 approved these changes

2024-11-04 19:08 UTC, merged