Add new blog post - mirrord
metalbear-co/metalbear.co pull request #12
Opened 2022-06-24 20:41 UTC by infiniteregrets

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +contributors: ["Mehul Arora"]
create a contributor page similar to the others.

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +title: "mirrord internals - hooking libc functions and fixing bugs"
Going low to get high (results) - Practical guide to hooks in Rust

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +description: "writing detours"
Dev blog on how we hook libc in mirrord to provide seamless developer experience

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +title: "mirrord internals - hooking libc functions and fixing bugs"
(feel free to change it ofc, that's a suggestion)

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +description: "writing detours"
(feel free to change it ofc, that's a suggestion)

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +“Is mirrord some kind of ptrace magic?”, that’s what I exactly thought when I was introduced to this idea of “mirroring traffic”. But to my surprise, the idea and design behind mirrord are completely
student -> junior dev

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +“Is mirrord some kind of ptrace magic?”, that’s what I exactly thought when I was introduced to this idea of “mirroring traffic”. But to my surprise, the idea and design behind mirrord are completely
maybe something like
"When I was told about mirrord implemented using hooks, I could imagine how it can be done, but as I started actively developing I was..."

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +## What is mirrord? 🐻
bear -> mirror emoji imo

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +Overriding these libc functions on different systems would have been a difficult task and this is where Frida-gum comes to save the day through its [inline hooking interceptor](https://github.com/fri
add DYLD

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +mirrord lets you run a local process in the context of a cloud service, which means we can test our code on staging, without actually deploying it there. This leads to shorter feedback loops (you don
link

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +title: "mirrord internals - hooking libc functions and fixing bugs"
overall comment - change image names to longer descriptions and add alts.
longer names -> better SEO
alts -> for accessibility (also SEO)

2022-06-27 18:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +## Mirroring network traffic & web servers 💻
this doesn't render well on my (big) screen -> emoji is on next line. maybe just present simple (Mirror) to keep it shorter

2022-06-27 18:36 UTC, infiniteregrets commented on content/en/blog/mirrord-internals/index.md
> +title: "mirrord internals - hooking libc functions and fixing bugs"
The blogpost is not that rusty though, although i like initial half of the title

2022-06-27 18:59 UTC, aviramha requested changes
Overall looking good. I think more examples from the code would be nice though.

2022-06-27 18:59 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +Overriding these libc functions on different systems would have been a difficult task and this is where Frida-gum comes to save the day through its [inline hooking interceptor](https://github.com/fri
maybe just few words though then expand in footnote?

2022-06-27 18:59 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +I want to do a quick walkthrough of how a simple webserver would work when run with mirrord and how this led me to find my first bug! So, in general, web servers implement the flow of creating a sock
more common is to have a select between listen, accept, so I would add a foot note clarifying it.

2022-06-27 18:59 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +Referring to the notes on the Linux manual for [listen](https://man7.org/linux/man-pages/man2/listen.2.html#NOTES):
Add numbering to each frame so people will know when does it starts/end.. maybe there's a better way to control it (check out if there's something?)

2022-06-27 18:59 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +To bind an address to the socket descriptor returned by the `socket` system call, [bind](https://man7.org/linux/man-pages/man2/bind.2.html) is called. Our detour for bind doesn’t really do much becau
and add the collected info from the bind?

2022-06-27 18:59 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +To start accepting connections on our socket, we have to mark the socket as passive using the [listen](https://man7.org/linux/man-pages/man2/listen.2.html) system call. There are quite a few things h
mark as passive? I don't think that's a term being used.. mark as listening maybe

2022-06-27 18:59 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +{{<figure src="listen.gif" height="100%" width="100%">}}
`getsockopt` -> `getsockname`

2022-06-27 18:59 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +- Call libc’s `getsockopt` to get the port that was assigned to our address. We call this our “fake port”.
`getsockopt` -> `getsockname`

2022-06-27 18:59 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +- Node is into some voodoo black magic and has decided to screw with me this time.
avoid usage of `voodoo` and `black` magic as it might be seen as offensive

2022-06-27 18:59 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +Checkout our open issues on the [GitHub issue tracker](https://github.com/metalbear-co/mirrord/issues), any kind of contribution is welcome!
Please feel free to provide feedback to this blog post to my email and or discord, also welcome to open an issue/send a PR for any suggestion.

2022-06-27 19:16 UTC, aviramha commented on content/en/blog/mirrord-internals/index.md
> +title: "mirrord internals - hooking libc functions and fixing bugs"
I think with few more examples it is :)

2022-06-27 19:39 UTC, infiniteregrets commented on content/en/blog/mirrord-internals/index.md
> +title: "mirrord internals - hooking libc functions and fixing bugs"
On it

2022-06-27 19:41 UTC, infiniteregrets commented on content/en/blog/mirrord-internals/index.md
> +“Is mirrord some kind of ptrace magic?”, that’s what I exactly thought when I was introduced to this idea of “mirroring traffic”. But to my surprise, the idea and design behind mirrord are completely
Hmm, not sure abt the second one but changed it to Junior Engineer

2022-06-27 20:23 UTC, infiniteregrets commented on content/en/blog/mirrord-internals/index.md
> +To start accepting connections on our socket, we have to mark the socket as passive using the [listen](https://man7.org/linux/man-pages/man2/listen.2.html) system call. There are quite a few things h
passive is picked from the linux manpage

2022-06-27 20:28 UTC, infiniteregrets commented on content/en/blog/mirrord-internals/index.md
> +- Node is into some voodoo black magic and has decided to screw with me this time.
changed it to sorcery

2022-07-04 13:33 UTC, aviramha approved these changes

2022-07-04 13:34 UTC, merged