Blogpost: Writing a Kubernetes Operator/Controller
metalbear-co/metalbear.co pull request #43
Opened 2023-03-02 12:52 UTC by DmitryDodzin

2023-03-03 11:06 UTC, eyalb181 requested changes

2023-03-03 11:06 UTC, eyalb181 commented on content/en/blog/kubenetes-operator/index.md
> +*A small note on the example structure it is broken into 3 steps each in its respective dir, each step is built upon the previous step with prebuilt images[\*](https://github.com/metalbear-co/farm-op
```suggestion
*Note that the example repository is divided into three steps, each in its respective directory, and each with its prebuilt image.[\*](https://github.com/metalbear-co/farm-operator/pkgs/container/farm-operator).*
```

2023-03-03 11:06 UTC, eyalb181 commented on content/en/blog/kubenetes-operator/index.md
> +{{<figure src="apiservicelist-return-value.png" alt="Json result from /apis/farm.example.com/v1alpha" height="100%" width="100%">}}
Can't this be a code snippet?

2023-03-03 11:06 UTC, eyalb181 commented on content/en/blog/kubenetes-operator/index.md
> +1. First, let’s talk about adding a new resource to be handled by the operator.
Add a title before this section, something like Coding our Operator

2023-03-03 11:06 UTC, eyalb181 commented on content/en/blog/kubenetes-operator/index.md
> +Our operator is now running locally, but stealing requests that are being sent to the operator deployment in the cluster!
Maybe add another screenshot of the local operator logging the request

2023-03-03 12:09 UTC, DmitryDodzin commented on content/en/blog/kubenetes-operator/index.md
> +{{<figure src="apiservicelist-return-value.png" alt="Json result from /apis/farm.example.com/v1alpha" height="100%" width="100%">}}
It certainly can now that I think about it

2023-03-05 09:29 UTC, DmitryDodzin commented on content/en/blog/kubenetes-operator/index.md
> +Our operator is now running locally, but stealing requests that are being sent to the operator deployment in the cluster!
Currently there are no logs in the farm-operator, probably need to add a println or something

2023-03-06 09:09 UTC, eyalb181 requested changes

2023-03-06 09:09 UTC, eyalb181 commented on content/en/blog/kubenetes-operator/index.md
> +## Using benefits of Operators
```suggestion
## Using Existing Resources
```

2023-03-06 09:09 UTC, eyalb181 commented on content/en/blog/kubenetes-operator/index.md
> +Implementing APIService lets us do is to provide access to existing resources but modify or enrich them before returning them to the user. All this without some complex synchronisation because you ca
```suggestion
One thing an APIService lets us do is provide access to existing resources, but modify or enrich them before returning them to the user. In this case, Kubernetes manages persistence for these resources, and all our operator has to do is retrieve them using the Kubernetes API. 
```

2023-03-09 12:25 UTC, merged