Blogpost: introducing targetless mode
metalbear-co/metalbear.co pull request #51
Opened 2023-05-24 21:05 UTC by t4lz

2023-05-25 13:35 UTC, eyalb181 requested changes

2023-05-25 13:35 UTC, eyalb181 commented on content/en/blog/introducing-targetless/index.md
> +description: "A short introduction to the new targetless mode of mirrord, explaining its main use-cases."
Also how about adding a meme or something?

2023-05-25 17:11 UTC, t4lz commented on content/en/blog/introducing-targetless/index.md
> +title: "Easy K8S Connectivity for Local Utils"
Added linebreaks.

2023-05-25 21:07 UTC, eyalb181 commented on content/en/blog/introducing-targetless/index.md
> +title: "Easy K8S Connectivity for Local Utils"
They're not showing in the preview

2023-05-25 21:39 UTC, t4lz commented on content/en/blog/introducing-targetless/index.md
> +title: "Easy K8S Connectivity for Local Utils"
Forgot to push 🤦

2023-05-26 09:10 UTC, eyalb181 commented on content/en/blog/introducing-targetless/index.md
> +description: "A short introduction to the new targetless mode of mirrord, explaining its main use-cases."
For your consideration:

![image](https://github.com/metalbear-co/metalbear.co/assets/5508354/841f4112-f57f-40a6-974a-ea9e92e1ae99)

2023-05-26 09:10 UTC, eyalb181 requested changes
Looks good, one last thing: we're planning to publish on Monday, so please change the date to Monday morning

2023-06-04 14:49 UTC, eyalb181 approved these changes

2023-06-04 14:49 UTC, merged