Add mirrord vs TP blog post
metalbear-co/metalbear.co pull request #56
Opened 2023-07-07 16:09 UTC by eyalb181

2023-07-07 16:31 UTC, meowjesty commented on content/en/blog/mirrord-vs-telepresence/index.md
> +7. mirrord is a tool for developers, and as such, in addition to a CLI tool, it also comes as an **IDE plugin for either VS Code or the IntelliJ IDEs**. This is the most popular way to use mirrord, w
```suggestion
7. mirrord is a tool for developers, and as such, in addition to a CLI tool, it also comes as an **IDE plugin for both VS Code and the IntelliJ IDEs**. This is the most popular way to use mirrord, where it naturally fits into the existing development workflow.
```

2023-07-07 16:40 UTC, meowjesty requested changes
Out of focus image?

Can we turn this into svg / text?

2023-07-07 16:40 UTC, meowjesty commented on content/en/blog/mirrord-vs-telepresence/cli-command.png
Image is blurry on the site!

2023-07-09 05:25 UTC, meowjesty approved these changes
🐻 👍

2023-07-09 05:26 UTC, infiniteregrets requested changes
content/en/blog/mirrord-vs-telepresence/mirrord-vs-telepresence.png is also blurry

2023-07-09 12:19 UTC, eyalb181 commented
> content/en/blog/mirrord-vs-telepresence/mirrord-vs-telepresence.png is also blurry

@infiniteregrets Try now

2023-07-09 14:08 UTC, infiniteregrets approved these changes

2023-07-09 14:19 UTC, merged