Post for the outgoing traffic filter feature.
metalbear-co/metalbear.co pull request #57
Opened 2023-08-24 15:16 UTC by meowjesty

2023-08-24 18:31 UTC, eyalb181 requested changes

2023-08-24 18:31 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +{ feature": { "network": { "outgoing": { "filter": { "local": ["app-db"] } } } } }
Format this so it isn't a one-liner

2023-08-24 18:31 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +- `config.json` where app sends traffic to local database
This doesn't look good as a bullet. Maybe make it part of the paragraph leading up to it.

2023-08-24 18:31 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +## The setup 📋
```suggestion
## The Setup 📋
```

2023-08-24 18:31 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +## The example 💾
```suggestion
## The Example 💾
```

2023-08-24 18:31 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +- retrieve `uwu-app` service port
```suggestion
- retrieve `uwu-app`'s service port
```

2023-08-24 18:31 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +$ curl -d "Hey, are you enjoying mirrord? Why not star us on github? It would be very cool of you." -X POST  http://192.168.49.2:3003
Major horizontal scrolling going on here, can you see if we can wrap the text?

2023-08-24 18:31 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +## The feature 🔃
```suggestion
## The Feature 🔃
```

2023-08-24 18:31 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +# The title
You can remove this

2023-08-24 18:51 UTC, meowjesty commented on content/en/blog/outgoing-traffic-filter/index.md
> +$ curl -d "Hey, are you enjoying mirrord? Why not star us on github? It would be very cool of you." -X POST  http://192.168.49.2:3003
We can, but the command will look weird.

```sh
curl -d "Hey, are you enjoying mirrord? 
Why not star us on github? It would be very cool of you." 
-X POST  http://192.168.49.2:3003/
```

2023-08-24 18:51 UTC, meowjesty commented on content/en/blog/outgoing-traffic-filter/index.md
> +$ curl -d "Hey, are you enjoying mirrord? Why not star us on github? It would be very cool of you." -X POST  http://192.168.49.2:3003
Or something along those lines.

2023-08-25 07:24 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +$ curl -d "Hey, are you enjoying mirrord? Why not star us on github? It would be very cool of you." -X POST  http://192.168.49.2:3003
Which lines

2023-08-25 07:31 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +$ curl -d "Hey, are you enjoying mirrord? Why not star us on github? It would be very cool of you." -X POST  http://192.168.49.2:3003
Also I think the weird looking command is better than the alternative

2023-08-25 14:08 UTC, meowjesty commented on content/en/blog/outgoing-traffic-filter/index.md
> +$ curl -d "Hey, are you enjoying mirrord? Why not star us on github? It would be very cool of you." -X POST  http://192.168.49.2:3003
Multiline now.

2023-08-25 14:40 UTC, eyalb181 requested changes

2023-08-25 14:40 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +# The Traffic Police 🚨 - Controlling outgoing traffic with mirrord
Remove the title from here

2023-08-25 14:40 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +So, you've been using mirrord to simplify your development process (if you haven’t, go here!). Naturally, you want the traffic from the app you're debugging to go through the cluster environment, so
Add link to "go here"

2023-08-25 14:40 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +With the new filter, you can specify whether your app’s outgoing traffic should be sent locally or remotely based on its destination. If we take the example above, with the database running in the cl
```suggestion
With the new filter, you can specify whether your app’s outgoing traffic should be sent locally or remotely based on its destination. If we take the example above, with the database running in the cluster as a service `app-db` on port `7777`, and locally on the same port, you can select which database your app will be talking to. Here is a sample `config.json` for this use case:
```

2023-08-25 14:44 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +lead: "Introducing the new outgoing traffic control feature for mirrord"
```suggestion
lead: "Introducing the new outgoing traffic filter feature for mirrord"
```

2023-08-25 19:48 UTC, eyalb181 requested changes

2023-08-25 19:48 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +- starts the `uwu-app` with mirrord
Remove this

2023-08-25 19:48 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +[^1]: We're setting `incoming` traffic to `steal`, but mirrord also supports traffic `mirror`ing, and traffic `steal`ing with a filter, you can see what's supported [here](https://mirrord.dev/docs/ov
```suggestion
[^1]: We're setting `incoming` traffic to `steal`, but mirrord also supports traffic `mirror`ing, and traffic `steal`ing with a filter. You can see all the options [here](https://mirrord.dev/docs/overview/configuration/#feature-network-incoming).
```

2023-08-25 21:57 UTC, meowjesty commented on content/en/blog/outgoing-traffic-filter/index.md
> +- starts the `uwu-app` with mirrord
wow eyal, you really asked me to remove line 69

2023-08-25 22:01 UTC, eyalb181 commented on content/en/blog/outgoing-traffic-filter/index.md
> +- starts the `uwu-app` with mirrord
nice :(

2023-08-25 22:01 UTC, eyalb181 reviewed
LGTM! Please change the date to Monday morning before you merge.

2023-08-25 22:02 UTC, eyalb181 approved these changes

2023-08-26 07:35 UTC, aviramha commented on content/en/blog/outgoing-traffic-filter/index.md
> +In this case, when your app tries to resolve the `app-db` hostname it’ll do so locally locally (instead of in-cluster), meaning that traffic which would normally go to the cluster’s `app-db` will be
locally locally?

2023-08-26 17:27 UTC, merged