add "Scaling-Out Development Environment" by Tanjim Hossain
metalbear-co/metalbear.co pull request #64
Opened 2023-12-21 18:26 UTC by audacioustux

Please make any required changes as needed. Also, I think there's a problem with the yaml parser. 
![image](https://github.com/metalbear-co/metalbear.co/assets/7238675/5ad51b44-0005-4684-930b-e76dc086a888)

Not sure if the formatting is good enough, as I had to port the whole thing from notion to markdown. I think the "weight" attribute of the post should also be set to a higher value (currently not set).

2023-12-21 18:27 UTC, audacioustux commented
@aviramha 👋🏽

2023-12-24 17:13 UTC, eyalb181 requested changes
Nice! Made a first round of comments.

2023-12-24 17:13 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +Soo, how ‘bout I offload some of the compute intensive stuffs to remote machine, or maybe cloud? Although, that introduces some other factors like cloud cost, internet connectivity…, what if you have
```suggestion
So, how ‘bout I offload some of the compute intensive stuff to a remote machine, or maybe the cloud? Although, that introduces some other factors like cloud cost, internet connectivity… what if you have an old machine laying around in your house? That’s exactly what I did at some point.
```

2023-12-24 17:13 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +1. **Re-producibility:** So, you have all the containers with their configurations specified in a docker-compose file, great! All the platform needs, including the other services you have as dependen
```suggestion
1. **Reproducibility:** So, you have all the containers with their configurations specified in a docker-compose file, great! All the platform needs, including the other services you have as dependencies (if you’re into ~~micro~~-services) are now accessible to your application, and reproducible with a simple `docker compose up`. Boom, done! But what about the CLI tools, desktop apps, IDE extensions, and so on? Maybe you or your teammates each have multiple machines for their development work. It’s not only the platform, or the application you’re working on that should be containerized, but also the whole **Dev Environment!**
```

2023-12-24 17:13 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    because of the constraints you have in your local dev setup? Not so ideal, right? In this day & age, typically your app should be ready for multi-instance deployment, or even multi-region for HA.
```suggestion
    because of the constraints you have in your local dev setup? Not so ideal, right? In this day & age, typically your app should be ready for multi-instance deployment, or even multi-region for HA. It’s hard to anticipate what would happen in that kind of production dynamic, if you only ever deployed a single instance of the app in a docker compose manifest. Also, if your target deployment platform is Kubernetes (EKS, K3s, AKE, GKE, OKE, CIVO etc.), why docker compose!? why docker!? why containers!? ahem… ok, I’ll explain the last one, I promise 🤞
```

2023-12-24 17:13 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    Yah, it’s Massive! But my point is, many of those tools are not very easy to configure in simple compose files. They may not have any detail of the required setup, other than just a helm or Kuber
```suggestion
    Yah, it’s massive! But my point is, many of those tools are not very easy to configure in simple compose files. They may not have any detail of the required setup, other than just a Helm or Kubernetes manifests. That means you’ll face some issues if your application architecture is not too simple, or the tools you use are from a recent generation.
```

2023-12-24 17:13 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +4. **Change-Build-Test (CBT) Performance:** How do you containerize your app for dev environment? Maybe you don’t do that, instead use port bindings to expose all the dependencies you have on other s
```suggestion
4. **Change-Build-Test (CBT) Performance:** How do you containerize your app for the dev environment? Maybe you don’t do that, and instead use port bindings to expose all the dependencies you have on other services, and access them from your app, running as a local process. So, there’re 4 options here:
```

2023-12-24 17:13 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    1. Build your app locally, copy the final artifact to container image (using COPY in Dockerfile for example) - **Cons:** Increased container build context sync time - due to the nature of build a
```suggestion
    1. Build your app locally, copy the final artifact to a container image (using COPY in Dockerfile for example) - **Cons:** Increased container build context sync time - due to the nature of build artifacts (e.g., large in size, hard to sync only the delta of the change) **Pros:** Potentially re-uses the local artifacts that your IDE may have already created, reducing redundant work!
```

2023-12-24 17:13 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    2. Sync codebase (mount) inside container. In this case, the hot-reload kind of stuffs are intended to happen inside the container. This may not work though in windows machines due to some issues
```suggestion
    2. Sync codebase (mount) inside container. In this case, the hot-reload kind of stuff is intended to happen inside the container. This may not work in Windows machines though, due to some issues with filesystem event propagation to the container from the host (not sure if the issue is now fixed or not). **Cons:** significant amount of redundant work by the IDE, and process (e.g., compiler, bundler, etc.) inside the container on each code change. **Pros:** only the particular changed file can be synced, greatly improves the feedback loop in case the container runs on a remote host.
```

2023-12-24 17:13 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    3. Using Tilt, Scaffold, etc. Tilt for example can be used to combine of both (a) and (b) [https://docs.tilt.dev/example_java.html](https://docs.tilt.dev/example_java.html) **Cons:** debugging ca
```suggestion
    3. Using Tilt, Skaffold, etc. Tilt for example can be used to combine of both (a) and (b) [https://docs.tilt.dev/example_java.html](https://docs.tilt.dev/example_java.html) **Cons:** debugging can be hard in certain languages and runtimes - due to the fact that the application process runs inside the container. **Pros:** Fast enough feedback loop / CBT cycle, whether the deployment target resides on the same machine or remote (remote k8s cluster or docker context)
```

2023-12-24 17:13 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +I think we should talk / discuss more about the development environments of our software, it’s no-less important than the production environment, and should strive to improve it as much as possible.
```suggestion
I think we should talk / discuss more about the development environments of our software, it’s no less important than the production environment, and we should strive to improve it as much as possible. In the beginning, it may feel like waste of time… but in the end, it may still look the same 😅, because the way we take things for granted, and tends to not be seeing how past actions leads to the present. As I have to work in DevOps / Platform Engineering stuffs, I had to solve some of dev environment issues not as “optional” but “mandatory” things. In the rest of this post, I’ll introduce or explain some of the tools and approaches that made my life much easier. Also, I think most of it can be applicable in a whole organization scale and save a lot of paid employee hours!
```

2023-12-24 17:13 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +Kubernetes, without any doubts, have a steep learning curve. Not everyone involved in a project should be well-versed in 100s of CRDs and yaml manifests!
```suggestion
Kubernetes, without any doubts, has a steep learning curve. Not everyone involved in a project should be well-versed in 100s of CRDs and yaml manifests!
```

2023-12-24 17:17 UTC, audacioustux commented on content/en/blog/scaling-out-development-environment/index.md
> +Kubernetes, without any doubts, have a steep learning curve. Not everyone involved in a project should be well-versed in 100s of CRDs and yaml manifests!
Damn, that's a lot of typos, my bad, Thanks! LGTM.

2023-12-24 17:23 UTC, audacioustux reviewed
LGTM, Thanks again!

2023-12-26 09:41 UTC, eyalb181 requested changes

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +draft: false
```suggestion
draft: false
weight: 50
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +draft: false
(This is needed for the post to show up in the correct place)

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +title: "Scaling-Out Development Environment"
```suggestion
title: "Scaling Out Development Environments"
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +lead: "mirrord to close the gap between Dev & Prod"
```suggestion
lead: "Using mirrord to close the gap between Dev & Prod"
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +2. **Dev-Prod Parity:** Are you willing to sacrifice the “Twelve-Factor App Methodology” - [Twelve-Factor App methodology](https://en.wikipedia.org/wiki/Twelve-Factor_App_methodology)
```suggestion
2. **Dev-Prod Parity:** Are you willing to sacrifice the [“Twelve-Factor App Methodology”] (https://en.wikipedia.org/wiki/Twelve-Factor_App_methodology)
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +2. **Dev-Prod Parity:** Are you willing to sacrifice the “Twelve-Factor App Methodology” - [Twelve-Factor App methodology](https://en.wikipedia.org/wiki/Twelve-Factor_App_methodology)
and delete the newline before "because" please

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +3. **CNCF Landscape & Kubernetes:** Have you seen the CNCF Landscape? [Cloud Native Landscape](https://landscape.cncf.io/)
```suggestion
3. **CNCF Landscape & Kubernetes:** Have you seen the [CNCF Landscape](https://landscape.cncf.io/)?
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    1. Build your app locally, copy the final artifact to a container image (using COPY in Dockerfile for example) - **Cons:** Increased container build context sync time - due to the nature of build
```suggestion
    1. Build your app locally, copy the final artifact to a container image (using COPY in Dockerfile for example).<br> **Cons:** Increased container build context sync time - due to the nature of build artifacts (e.g., large in size, hard to sync only the delta of the change) <br>**Pros:** Potentially re-uses the local artifacts that your IDE may have already created, reducing redundant work!
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    1. Build your app locally, copy the final artifact to a container image (using COPY in Dockerfile for example) - **Cons:** Increased container build context sync time - due to the nature of build
We have to sort out our CSS, but until then we need an explicit <br> here for a newline 🤦

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    2. Sync codebase (mount) inside container. In this case, the hot-reload kind of stuff is intended to happen inside the container. This may not work in Windows machines though, due to some issues
```suggestion
    2. Sync codebase (mount) inside container. In this case, the hot-reload kind of stuff is intended to happen inside the container. This may not work in Windows machines though, due to some issues with filesystem event propagation to the container from the host (not sure if the issue is now fixed or not). <br>**Cons:** significant amount of redundant work by the IDE, and process (e.g., compiler, bundler, etc.) inside the container on each code change. <br>**Pros:** only the particular changed file can be synced, greatly improves the feedback loop in case the container runs on a remote host.
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    3. Using Tilt, Skaffold, etc. Tilt for example can be used to combine of both (a) and (b) [https://docs.tilt.dev/example_java.html](https://docs.tilt.dev/example_java.html) **Cons:** debugging ca
```suggestion
    3. Using Tilt, Skaffold, etc. Tilt for example can be used to combine of both (a) and (b) [https://docs.tilt.dev/example_java.html](https://docs.tilt.dev/example_java.html) <br>**Cons:** debugging can be hard in certain languages and runtimes - due to the fact that the application process runs inside the container. <br>**Pros:** Fast enough feedback loop / CBT cycle, whether the deployment target resides on the same machine or remote (remote k8s cluster or docker context)
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    4. No containerization. **Cons:** hard to match production environment **Pros:** bare-minimal overhead
```suggestion
    4. No containerization. <br>**Cons:** hard to match production environment <br>**Pros:** bare-minimal overhead
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +    3. Using Tilt, Skaffold, etc. Tilt for example can be used to combine of both (a) and (b) [https://docs.tilt.dev/example_java.html](https://docs.tilt.dev/example_java.html) **Cons:** debugging ca
```suggestion
    3. Using Tilt, Skaffold, etc. Tilt for example [can be used to combine of both (a) and (b)](https://docs.tilt.dev/example_java.html) **Cons:** debugging can be hard in certain languages and runtimes - due to the fact that the application process runs inside the container. **Pros:** Fast enough feedback loop / CBT cycle, whether the deployment target resides on the same machine or remote (remote k8s cluster or docker context)
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +I think we should talk / discuss more about the development environments of our software, it’s no less important than the production environment, and we should strive to improve it as much as possibl
```suggestion
I think we should talk / discuss more about the development environments of our software, it’s no less important than the production environment, and we should strive to improve it as much as possible. In the beginning, it may feel like waste of time… but in the end, it may still look the same 😅, because the way we take things for granted, and tend to not be seeing how past actions leads to the present. As I have to work in DevOps / Platform Engineering stuff, I had to solve some of dev environment issues not as “optional” but “mandatory” things. In the rest of this post, I’ll introduce or explain some of the tools and approaches that made my life much easier. Also, I think most of it can be applicable in a whole organization scale and save a lot of paid employee hours!
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +{{<figure src="kelsey-hightower-tweet.png" alt="Kubernetes is a platform for building platforms. It's a better place to start; not the endgame" height="100%" width="100%">}}
```suggestion
{{< tweet user="kelseyhightower" id="935252923721793536" >}}
```

2023-12-26 09:41 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +date: 2023-12-21T0:00:00+00:00
```suggestion
date: 2024-01-02T0:00:00+00:00
```

2023-12-26 16:09 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +      cargo:watch:
```suggestion
      cargo:watch :
```

2023-12-26 16:09 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/index.md
> +      cargo:watch:
The emoji thing is an [issue with Hugo](https://github.com/gohugoio/hugo/issues/7332), the framework we use for our website. I think adding a space here is the cleanest solution (though still pretty ugly)

2023-12-26 16:09 UTC, eyalb181 commented on content/en/blog/scaling-out-development-environment/kelsey-hightower-tweet.png
This can be deleted now

2023-12-26 16:14 UTC, audacioustux commented on content/en/blog/scaling-out-development-environment/index.md
> +      cargo:watch:
good enough workaround, I think.

2023-12-26 16:16 UTC, audacioustux commented on content/en/blog/scaling-out-development-environment/kelsey-hightower-tweet.png
done.

2023-12-26 16:25 UTC, eyalb181 approved these changes
Thanks! We'll release this on January 2nd

2023-12-26 16:25 UTC, merged