uploading the IDP article
metalbear-co/metalbear.co pull request #75
Opened 2024-03-22 07:55 UTC by Anita-ihuman

2024-03-23 10:54 UTC, eyalb181 requested changes

2024-03-23 10:54 UTC, eyalb181 commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +  - Developer experince
```suggestion
  - devex
```

2024-03-23 10:54 UTC, eyalb181 commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +  - Internal Developer Portals
```suggestion
  - idps
```

2024-03-23 10:54 UTC, eyalb181 commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +  - Internal Developer Platforms
Remove

2024-03-23 10:54 UTC, eyalb181 commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +images: ["designer.png"]
Image is not used anywhere in the article

2024-03-23 10:54 UTC, eyalb181 commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +images: ["designer.png"]
Also, put a MetalBear in there to make it a bit less generic

2024-03-25 09:58 UTC, eyalb181 approved these changes

2024-03-25 10:06 UTC, t4lz commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +* **Backstage:** [Backstage](https://backstage.io/) is an open-source IDP that allows developers to manage services, infrastructure, documentation, and more, all within a single platform. It features
> security capabilities with no compliance

I am a bit confused by this part. Maybe it should say something like:

> ... and security capabilities, and no compliance solutions

or

> ... and security capabilities, but no compliance solutions

I don't know IDPs or backstage so I can't say what's right here, just that I don't understand that sentence as it is.

2024-03-25 10:33 UTC, t4lz reviewed
Very nice post. Hadn't read everything yet, but I don't have a lot to say on the contents anyways as I don't know anything about IDPs.

Some headlines need to be fixed, and there are some other optional suggestions.

2024-03-25 10:33 UTC, t4lz commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +# What is an Internal Developer Platform?
```suggestion
## What is an Internal Developer Platform?
```

Shouldn't be bigger than the main title.

2024-03-25 10:33 UTC, t4lz commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +# Wrapping up
```suggestion
## Wrapping up
```

2024-03-25 10:33 UTC, t4lz commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +|  | Category | Pricing  |Features |
I think it's excellent you included a table. Could be cool to split the features into their own columns and then mark yes/no or check-mark/empty or check-mark/X with green/red colors for each platform, like in these examples:
- https://en.wikipedia.org/wiki/Comparison_of_database_administration_tools#General
- https://en.wikipedia.org/wiki/Comparison_of_programming_languages#General_comparison
- [some examples from google images](https://www.google.com/search?sca_esv=d1ba00635c671747&gbv=2&q=feature+comparison+table&uds=AMwkrPutq-TxOnWtSQaB1WSjWHshcUtBdL6pdEQz_5MvGqVyzfTgsaGjyAvzEPMY1Mfx9qEXLJWyyzeXRmXChrAeVYZpmUyfnqQKoCj7XUqgKmZYznOWewP7e-R78LHaSTZkhV5NtwhyNXz84ncIIm85JkZ4-enVWV-3C4U593B8wyk97lAVToViDBq7Hi8eX7gHojJ-lAp_vAlBXULl3_iZG2h07ONDbrPEjmjJvC51demrU4XrvhSKrCDdticJQIa1O-CHjw_AbeFhaDYIzaMmr_nRSMgq7yWkD7ENdqElT695UGXaTZU&udm=2&prmd=ivnbz&sa=X&ved=2ahUKEwi7hOKGmY-FAxUoTKQEHSZoDLkQtKgLegQILRAB&biw=1615&bih=1060&dpr=1#vhid=lahg9eTHZKl0MM&vssid=mosaic)

2024-03-25 10:46 UTC, t4lz commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +* **Humanitec:** [Humanitec](https://developer.humanitec.com/introduction/overview/) is a platform orchestrator that offers platform engineers and developers a self-service infrastructure for buildin
> Humanitec offers minimal observability and scalability

I think adding "only" could make it clearer this is negative

> Humanitec only offers minimal observability and scalability

Also in other places in the text I would suggest adding "only" somewhere before the word "minimal".
Could just be me though.

2024-03-25 11:04 UTC, Anita-ihuman commented on content/en/blog/comparison-of-internal-developer-platforms/index.md
> +* **Humanitec:** [Humanitec](https://developer.humanitec.com/introduction/overview/) is a platform orchestrator that offers platform engineers and developers a self-service infrastructure for buildin
I think adding "only" gives a definite conclusion that there are no other challenges to the platform except these. However, a user with a different use case might encounter another issue that we did not mention.

2024-03-25 12:11 UTC, aviramha approved these changes

2024-03-25 12:57 UTC, eyalb181 approved these changes

2024-03-25 13:11 UTC, merged