add writers-program and cfp-program pages with revision
metalbear-co/metalbear.co pull request #85
Opened 2024-05-08 18:35 UTC by aviramha

2024-05-10 18:07 UTC, eyalb181 requested changes

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/writers-program/index.md
> +    We welcome applications from everyone, regardless of experience level. You must have some experience writing for a third party and are comfortable with receiving feedback on your writing.
```suggestion
    We welcome applications from everyone, regardless of experience or role. All we ask is that you be comfortable with receiving feedback on your writing.
```

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/writers-program/index.md
> +    - We do not publish posts that have appeared elsewhere.
```suggestion
    - We do not publish posts that have already been published somewhere else.
```

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/writers-program/index.md
> +    - Get paid: You can earn $150-$300 for each article you write that gets published.
Weird that this is the first time this is mentioned. Should probably be mentioned in the hero section. @Anita-ihuman @aviramha wdyt?

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/writers-program/index.md
> +    - Boost your portfolio: Showcase your writing skills and technical knowledge to potential employers.
```suggestion
    - Boost your portfolio: Showcase your writing skills and technical knowledge.
```

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +header_title: Talk About Mirrord
```suggestion
header_title: Talk About mirrord
```

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +  We are calling on mirrored users, contributors, developers, and engineers actively working with mirrord to represent mirrord at conferences worldwide. Got a presentation in mind? This is your chanc
```suggestion
  We are calling on mirrord users and contributors actively working with mirrord to talk about their takes and experiences with mirrord at conferences worldwide. Got a presentation in mind? This is your chance to share your knowledge and help spread the word about mirrord.
```

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +    - We will provide personalized assistance to help you deliver smooth presentations
```suggestion
    - We will provide personalized assistance to help you deliver a great presentation.
```

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +    - Subject matter experts: users and individuals with deep knowledge and proven experience with mirrord and its features.
```suggestion
    - Subject matter experts: users and individuals with deep knowledge and experience with mirrord.
```

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +    - mirrord enthusiasts: Passionate about mirrord's potential and eager to share its benefits with the world.
```suggestion
    - mirrord enthusiasts: people who are passionate about mirrord's potential and are eager to share its benefits with the world.
```

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +    - Engaging presenters: Ability to deliver captivating presentations that inspire and educate audiences.
```suggestion
    - Engaging speakers: speakers who can deliver captivating talks that inspire and educate technical audiences.
```

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +    - Individuals from diverse backgrounds and fields are encouraged to apply as long as your topic intersects with the mirrord capabilities.
```suggestion
    - Individuals from diverse backgrounds and fields are encouraged to apply as long as your topic intersects with mirrord.
```

2024-05-10 18:07 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +  - "Tell us about your talk: Briefly describe your proposed topic, the target audience, how it aligns with the themes of the conference, and demonstrates mirrord capabilities."
```suggestion
  - "Tell us about your talk: Briefly describe your proposed topic, the target audience, how it aligns with the themes of the conference, and demonstrates mirrord's capabilities and use cases."
```

2024-05-13 09:06 UTC, Anita-ihuman commented on content/en/pages/writers-program/index.md
> +    - Get paid: You can earn $150-$300 for each article you write that gets published.
I fixed this

2024-05-13 09:40 UTC, eyalb181 requested changes

2024-05-13 09:40 UTC, eyalb181 commented on content/en/pages/writers-program/index.md
> +    - Technical tutorials: Using mirrord for different use cases and within different stacks.
```suggestion
    - Technical tutorials: using mirrord for different use cases and within different stacks.
```

2024-05-13 09:40 UTC, eyalb181 commented on content/en/pages/writers-program/index.md
> +    - Deep dives: In-depth articles on technical concepts and technologies.
```suggestion
    - Deep dives: in-depth articles on technical concepts and technologies.
```

2024-05-13 09:40 UTC, eyalb181 commented on content/en/pages/writers-program/index.md
> +    - Best practices: Share tips and tricks for improving developer experience.
```suggestion
    - Best practices: share tips and tricks for improving developer experience.
```

2024-05-13 09:40 UTC, eyalb181 commented on content/en/pages/writers-program/index.md
> +    - Personal experiences: Share your own unique journey and lessons learned using mirrord in your software development cycle.
```suggestion
    - Personal experiences: share your own unique journey and lessons learned using mirrord in your software development cycle.
```

2024-05-13 09:40 UTC, eyalb181 commented on content/en/pages/writers-program/index.md
> +    - Get paid: You can earn $150-$300 for each article you write that gets published.
```suggestion
    - Get paid: you can earn $150-$300 for each article you write that gets published.
```

2024-05-13 09:40 UTC, eyalb181 commented on layouts/_default/writers-program.html
> +                            and more. All contents are credited to the authors and promoted across our social media,
```suggestion
                            and more. We'll pay you for any content that gets published, and all content is credited to the authors and promoted across our social media,
```

2024-05-13 09:40 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +  - "Pick your conferences: Indicate the specific conferences you plan to attend and present at."
The first letter after a ":" doesn't need to be capitalized - please fix where relevant.

2024-05-13 09:40 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +- label: needs
```suggestion
- label: requirements
```

2024-05-13 09:56 UTC, Anita-ihuman commented on content/en/pages/cfp-program/index.md
> +  - "Pick your conferences: Indicate the specific conferences you plan to attend and present at."
Fixed

2024-05-13 16:14 UTC, eyalb181 requested changes

2024-05-13 16:14 UTC, eyalb181 commented on content/en/pages/writers-program/index.md
> +    description: submit a brief application with a topic of interest and an outline, along with a writing sample that showcases your experience and writing skills.
The starts of the descriptions should be capitalized, e.g. Submit

2024-05-13 16:14 UTC, eyalb181 commented on content/en/pages/cfp-program/index.md
> +  We are calling on mirrord users and contributors actively working with mirrord to talk about their takes and experiences with mirrord at conferences worldwide. Got a presentation in mind? This is y
```suggestion
  We're inviting mirrord users to talk about their takes and experiences with mirrord at conferences worldwide. Have an idea for a mirrord-related conference talk or workshop? This is your chance to share your knowledge and help spread the word about mirrord.
```

2024-05-13 16:29 UTC, eyalb181 approved these changes

2024-05-13 17:01 UTC, merged